### ISSUE TITLE
Audiobook processing

### ISSUE THREAD

**Issue by ehwhattaugonnado** [RandomNinjaAtk/docker-readarr-extended#1]
Would it be possible to roll in an m4b processing script https://github.com/sandreas/m4b-tool to handle audiobooks that are multiple MP3 files?

**Comment by RandomNinjaAtk** [comment]
I looked at this a few times and couldn't find an easy way to do that. Sabnzbd-extended has a script that does something similar but it hasn't had much testing.

**Comment by ehwhattaugonnado** [comment]
Yeah I see an open PR on readarr for this as well. Seems that it would take a significant amount of work for it to work reliably without user intervetion.
